"""Send analysis reports by email via a simple, free SMTP server."""

import smtplib
from email.message import EmailMessage

from cfa.core.config import MAIL_FROM, SMTP_HOST, SMTP_PASS, SMTP_PORT, SMTP_USER


def is_configured() -> bool:
    return bool(SMTP_HOST and SMTP_USER and SMTP_PASS)


def send_email(to_email: str, subject: str, html: str) -> None:
    if not is_configured():
        raise RuntimeError("SMTP not configured (set SMTP_HOST, SMTP_USER, SMTP_PASS).")
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = MAIL_FROM
    msg["To"] = to_email
    msg.set_content("Your Customer Feedback Insight report is attached as HTML.")
    msg.add_alternative(html, subtype="html")
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as s:
        s.starttls()
        s.login(SMTP_USER, SMTP_PASS)
        s.send_message(msg)


def build_report_html(stats: dict) -> str:
    stats = stats or {}
    total = stats.get("total_reviews", 0)
    sd = stats.get("sentiment_distribution", {})
    concerns = stats.get("ranked_concerns", []) or []

    rows = "".join(
        f"<tr><td>{c.get('concern', '')}</td><td>{c.get('count', 0)}</td>"
        f"<td>{c.get('negative_pct', 0):.0f}%</td><td>{c.get('impact', 0)}</td></tr>"
        for c in concerns[:10]
    ) or "<tr><td colspan='4'>No concerns detected.</td></tr>"

    sent = "".join(f"<li>{k.capitalize()}: {v}</li>" for k, v in sd.items()) or "<li>No data</li>"

    return f"""
    <html><body style="font-family:Arial,sans-serif;color:#142b48">
      <h2>Customer Feedback Insight Report</h2>
      <p><strong>{total}</strong> reviews analyzed.</p>
      <h3>Sentiment</h3>
      <ul>{sent}</ul>
      <h3>Top Concerns</h3>
      <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse">
        <tr><th>Concern</th><th>Mentions</th><th>Negative</th><th>Impact</th></tr>
        {rows}
      </table>
      <p style="margin-top:24px;color:#8a96a8;font-size:12px">
        Generated by the Customer Feedback Insight System.
      </p>
    </body></html>
    """
